model_name: cat_boost
artifact_path: basic_cb

tag_key: "model"
tag_value: "basic CB"

module_name: "catboost"
class_name: "CatBoostRegressor"

params:
  iterations: [100, 200, 300]
  learning_rate: [0.01, 0.1, 0.2]
  depth: [3, 5, 7]
