model_name: gradient_boosting
artifact_path: basic_gb

tag_key: "model"
tag_value: "basic GB"

module_name: "sklearn.ensemble"
class_name: "GradientBoostingRegressor"

params:
  n_estimators: [100, 200, 300]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]
