defaults:
  - _self_

folds: 3

evaluation_metric: "neg_mean_squared_error"
cv_evaluation_metric: "mean_test_neg_mean_squared_error"

pyfunc_predict_fn: "predict"

metrics:
  neg_mean_squared_error: "neg_mean_squared_error"
  r2: "r2"

model_names: ["random_forest", "gradient_boosting"]
model_alias: "challenger"
model_number: 27

best_model_alias: "champion"
