data:
  path : "data_base/"
  raw_data_name : "sample"
  data_format : ".csv"
  version : 1
  sample_size: 1
  sample_name: "sample.csv"
  sample_folder: "data/samples"
gx:
  data_path : "data/samples/sample.csv"
  project_root_dir : "services"
  datasource_name : "pandas_datasource"
  asset_name : "csv_file"
  suite_name : "initial_data_validation"
  